In [1]:
import numpy as np

In [15]:
lst =  np.array([1, 2, 3, 4])
lst

array([1, 2, 3, 4])

In [17]:
type(lst)

numpy.ndarray

In [19]:
lst.shape

(4,)

In [21]:
lst.reshape(2, 2)

array([[1, 2],
       [3, 4]])

In [33]:
np.array([[1, 23, 4]], ndmin = 5)

array([[[[[ 1, 23,  4]]]]])

In [37]:
np.array([12+2j, 3], dtype =complex)

array([12.+2.j,  3.+0.j])

In [41]:
np.array([12, 3], dtype ='int64')

array([12,  3], dtype=int64)

In [45]:
np.array([12, 3], dtype =np.float32)

array([12.,  3.], dtype=float32)

In [57]:
np.array([12, 355], dtype =[('a', '<i2'), ('b', '<i8')]) # 2*8 -16 (little indian) and 8*8 - 64 (big indian): btween 16 - 64 bit 'a' -zero treminated byte, 'b' -byte

array([( 12,  12), (355, 355)], dtype=[('a', '<i2'), ('b', '<i8')])

In [67]:
n  =np.array([[1, 23, 4], [13, 56, 8], [657, 7, 9], [45, 7 ,8]])
n

array([[  1,  23,   4],
       [ 13,  56,   8],
       [657,   7,   9],
       [ 45,   7,   8]])

In [99]:
n[[0, 3],0::2]

array([[ 1,  4],
       [45,  8]])

In [101]:
np.mat([1,2 ,3])

matrix([[1, 2, 3]])

In [108]:
d = np.mat(n)

In [110]:
np.array(d)

array([[  1,  23,   4],
       [ 13,  56,   8],
       [657,   7,   9],
       [ 45,   7,   8]])

In [112]:
issubclass(np.matrix, np.ndarray)

True

In [114]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [120]:
arr = np.asarray([1, 2,3 ])
arr2 = np.asarray([23,  4, 5])
arr3 = np.asarray([1, 2,3 ])

In [118]:
arr is arr2 # diff address

False

In [124]:
arr = np.array([1, 2,3 ])
arr2 = np.array([23,  4, 5])
arr3 = np.array([1, 2,3 ])
arr is arr3

False

In [130]:
a = 10
b=10
a is b

True

In [134]:
arr2 = arr
arr2[0] = 22
arr

array([22,  2,  3])

In [136]:
arr2 = arr.copy() # deep copy
arr2[2] =0
arr

array([22,  2,  3])

In [140]:
a = 370
b= 370
a is b

False

In [142]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [144]:
np.fromfunction(lambda x , y: x==y, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [146]:
np.fromfunction(lambda x , y: x*y, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [150]:
np.arange(1, 4, 1)

array([1, 2, 3])

In [156]:
np.linspace(1 , 4, 10, retstep=True, endpoint=False)

(array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7]), 0.3)

In [166]:
np.logspace(5, 7, 5)

array([  100000.        ,   316227.76601684,  1000000.        ,
        3162277.66016838, 10000000.        ])

In [170]:
np.diag([[1, 2], [3, 4]])

array([1, 4])

In [172]:
np.diagflat([[1, 2], [3, 4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [174]:
np.diag([[1, 2], [3, 4]], k=-1)

array([3])

In [176]:
np.tri(3, 4, 1)

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [178]:
n = np.array([1, 2, 3])

In [180]:
n[n>2]

array([3])

In [184]:
# random Number
# uniform distribution
np.random.rand(3, 4)

array([[0.09166618, 0.87736785, 0.39411209, 0.63945154],
       [0.24679141, 0.93899349, 0.2987884 , 0.36067974],
       [0.86332635, 0.74595563, 0.59525199, 0.21781655]])

In [186]:
# standard normal distribution
np.random.randn(3,4 )

array([[-0.40285416,  2.15233633,  0.29448191,  0.04310718],
       [-0.24764493,  1.01732135,  1.53437185,  0.20230089],
       [-0.42161542,  0.94372974, -0.22959498,  0.6592859 ]])

In [190]:
np.random.randint(3, 10, 2)

array([3, 9])

In [196]:
n.reshape(1, -2223233)

array([[1, 2, 3]])

In [202]:
np.sort(arr, kind='merge')

array([ 2,  3, 22])